import { MetadataRoute } from 'next';

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: 'Googlebot',
        allow: '/',
        disallow: [
          '/dashboard',
          '/admin',
          '/cxbc/dashboard',
          '/cxbc/bills',
          '/cxbc/book',
          '/cxbc/settings',
          '/cxbc/shipments',
          '/cxbc/wallet',
          '/api',
          '/auth/kyc',
          '/onboarding',
          '/profile',
          '/wallet',
          '/vault',
          '/drafts',
          '/history',
          '/shipments',
          '/new-shipment',
          '/support',
          '/rate-calculator',
        ],
      },
      {
        userAgent: 'Bingbot',
        allow: '/',
        disallow: [
          '/dashboard',
          '/admin',
          '/cxbc/dashboard',
          '/api',
          '/auth/kyc',
          '/onboarding',
          '/profile',
          '/wallet',
          '/vault',
          '/drafts',
          '/history',
          '/shipments',
          '/new-shipment',
          '/support',
          '/rate-calculator',
        ],
      },
      {
        userAgent: '*',
        allow: '/',
        disallow: [
          '/dashboard',
          '/admin',
          '/cxbc/dashboard',
          '/cxbc/bills',
          '/cxbc/book',
          '/cxbc/settings',
          '/cxbc/shipments',
          '/cxbc/wallet',
          '/api',
          '/auth/kyc',
          '/onboarding',
          '/profile',
          '/wallet',
          '/vault',
          '/drafts',
          '/history',
          '/shipments',
          '/new-shipment',
          '/support',
          '/rate-calculator',
        ],
      },
    ],
    sitemap: 'https://courierx.in/sitemap.xml',
    host: 'https://courierx.in',
  };
}
